### ISSUE TITLE
API should allow for edits to existing operations

### ISSUE THREAD

**Issue by kcbabo** [fusesource/fuseide#150]
To change a mapping operation with the common API, you have to delete and re-add it, which is kinda dumb.  We should support basic edits which don't have side effects (e.g. requiring a new class mapping).  Some examples:
* Change the language and/or expression text for an expression mapping
* Change the variable name used as the source of a variable mapping
* Change the class name and/or method used in a custom mapping

**Comment by kcbabo** [comment]
Also added the ability to change the name or value of a variable in the dozer config.  One important distinction to make on variables ...  if you want to change the variable used *in* a mapping, then use VariableMapping.setVariable().  If you want to change the name or value of a variable in the configuration, then use Variable.setName() / Variable.setValue().

**Comment by kcbabo** [comment]
pushed

**Comment by jpav** [comment]
There is one problem with this: Since we now support new empty mappings in the GUI and the Expression class is no longer visible, I have no way to set an expression on the source without already having a saved mapping with a valid target model.  I need the Expression class to become a first-class public class again or some feasible alternative.

Also an FYI: The one place I'm still having to do the delete/re-add thing is when the user remove a custom function from a mapping, returning it to just a FieldMapping.

**Comment by kcbabo** [comment]
It's tough for me to say without seeing how you are handling empty mappings, but I assume you are using a placeholder of some sort instead of an instance of MappingOperation? 

The reason why I moved away from Variable and Expression being created independently is that the instances can't be backed by configuration in that state.  I'm sure we can come up with a viable alternative that satisfies all requirements, though.

We'll have to discuss the custom mapping approach.  Delete/re-add is fine for now, but maybe we can add a removeCustomization() or something similar to the API to preserve orderings of the mappings.  The one thing that's funky there is that removal of the custom mapping changes the actual object type of the MappingOperation (FieldMapping vs. CustomMapping).  We can fix that by changing customization to be a behavior of a FieldMapping vs. its own concrete type.

**Comment by jpav** [comment]
> It's tough for me to say without seeing how you are handling empty mappings, but I assume you are using a placeholder of some sort instead of an instance of MappingOperation?
> 

Yes, and I'm using an adapter for the config in conjunction with that. I can disable the setting of expressions for now an do a PR, but I'm also getting some new errors related to the new palette class that was added due to some missing libraries.

**Comment by jpav** [comment]
Actually, I guess I can get around this, too, using yet another placeholder for an expression. A little more towards the hackish side, but it would work.

**Comment by kcbabo** [comment]
OK, maybe we start with the hack and then figure out how the API should change to help support the UI more.

Where are you seeing errors with the palette class (build-time, runtime, validation in Eclipse)?  Are they fatal?  I built and ran with that code and it worked for me. :-)

**Comment by jpav** [comment]
Yeah, I’m guessing I know that that is, too: I accidentally did a mvn clean install from the fuseide root, realized my mistake, and cancelled the build in the middle.  I’m guessing the new dependencies are to some of that stuff.

**Comment by kcbabo** [comment]
Closing this issue for M4.  We can look at improving the API as a separate issue.
