### ISSUE TITLE
Add the ability to view/edit/delete endpoints defined in camel context

### ISSUE THREAD

**Issue by kcbabo** [fusesource/fuseide#153]
Right now, you can only see values of existing endpoints in the palette.  It would be nice to see endpoints defined within the camel context listed by id and provide some facility for edit/delete.

**Comment by jstrachan** [comment]
BTW we've been adding [some new forge commands for camel/fabric8](https://github.com/fabric8io/fabric8/issues?q=label%3Aforge+is%3Aclosed) such as to [add new components](https://github.com/fabric8io/fabric8/issues/3437) to a project (updating the pom.xml and generating spring/CDI DI to configure the component instance so its easy for folks to customize further the component settings) and are close to tackling a similar wizard to add new endpoints too.

* https://github.com/fabric8io/fabric8/blob/master/forge/addons/camel/src/main/java/io/fabric8/forge/camel/commands/project/CamelAddComponentInstanceCDICommand.java#L46
* https://github.com/fabric8io/fabric8/blob/master/forge/addons/camel/src/main/java/io/fabric8/forge/camel/commands/project/CamelAddComponentInstanceSpringCommand.java#L46

There's a [pending issue for a similar forge wizard for adding a new endpoint](https://github.com/fabric8io/fabric8/issues/2730) too (which is aware of the new camel 2.15 metadata & documentation etc).

Now that its looking like Fuse 6.2 and data-mapper can use camel 2.15 we should probably try unify all the forge stuff together into a single project so its easier to reuse and we avoid duplicating stuff.

**Comment by jpav** [comment]
Handled by [FUSETOOLS-1255](https://issues.jboss.org/browse/FUSETOOLS-1255)
