### ISSUE TITLE
Palette is missing some components from camel-core

### ISSUE THREAD

**Issue by kcbabo** [fusesource/fuseide#155]
The following components from camel-core are not represented in the palette:
* beanclass
* binding
* browse
* controlbus
* dataformat
* dataset
* direct
* directvm
* log
* mock
* properties
* ref
* scheduler
* seda
* stub
* test
* timer
* validator
* vm
* xslt

**Comment by kcbabo** [comment]
My opinion is that the following would be considered common:
* bean
* direct
* directvm
* language
* log
* seda
* vm
* xslt

**Comment by lhein** [comment]
most included now.
