### ISSUE TITLE
Change models in mappings to have the same parentage as those created within the config source/target models

### ISSUE THREAD

**Issue by kcbabo** [fusesource/fuseide#170]
_This was originally filed by John V in the data-mapper repository.  Moving it over to fuside._

> The addition of tying models to mappings helps, but I need this last piece to effectively provide highlighting of associated source and target elements in the model viewers when a mapping is selected. The problem now is, for instance, the model for Items in the ABCOrder model has no parent in the mapping, whereas it has an appropriate parent in the corresponding model under the config's source model.

**Comment by jpav** [comment]
This issue also affects the ability to provide search capability in the model viewers

**Comment by jpav** [comment]
With the changes to search capabilities in the model viewers, this is no longer necessary
