### ISSUE TITLE
Verify data format IDs exist on "Other" pages of New Transformation wizard

### ISSUE THREAD

**Issue by bfitzpat** [fusesource/fuseide#172]
There's a strange case now with the revised New Fuse Transformation wizard on the "Other" type for source and target. If you select a Java class and enter anything in the data format ID field, it will let you to the next page or finish. Unfortunately, right now I'm not validating that the ID actually exists we need to either offer a drop-down there or at least validate the text input to make sure that the ID is good.

**Comment by bfitzpat** [comment]
After talking with Keith, we'll make the field (currently a text box) into a drop-down with available data format ids.

**Comment by bfitzpat** [comment]
Created PR https://github.com/fusesource/fuseide/pull/178

**Comment by bfitzpat** [comment]
Can't find a way to decorate the label, but have changed the text color to red if there are no data format definitions available.

**Comment by lhein** [comment]
If you are using data binding you can specify validator and in that validator you could simply return something like return ValidationStatus.warning("bla") to switch to warning icons. It will decorate the txt field automatically. see https://github.com/fusesource/fuseide/blob/master/editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/propertysheet/AdvancedEndpointPropertiesSection.java#L296-L316 for example

**Comment by bfitzpat** [comment]
I was trying to avoid using another validator, but that's not a bad way to go.

**Comment by kcbabo** [comment]
pushed
