### ISSUE TITLE
Finish should be disabled on wizard completion

### ISSUE THREAD

**Issue by kcbabo** [fusesource/fuseide#179]
The finish option should be idempotent within the new transformation wizard.  Right now, you can click the Finish button multiple times and the editor seems to get into a weird state as a result.  Can we disable the Finish button once it's clicked?

**Comment by jpav** [comment]
Not familiar with the context here, but shouldn't the finish button close the wizard, and thus make its indempotence a moot point?

**Comment by kcbabo** [comment]
Waiting for the project build lifecycle to complete (and compile our generated model classes) is what keeps the wizard open for a bit:
https://github.com/fusesource/fuseide/blob/d7aeaabb408f35b57f09925a9933180c26ae363a/transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/editor/wizards/NewTransformationWizard.java#L146

**Comment by jpav** [comment]
A long running task like this is usually handled via a modal progress monitor that blocks the user from re-clicking the finish button, gives the user a visual indication of what's happening, and optionally may even allow me he user to cancel the operation (finish in this case). I'd assume the latter wouldn't apply here, but the other reasons would still apply.

**Comment by kcbabo** [comment]
To qualify "long-running" in this context, it's generally in the neighborhood of 1000-1500ms on my machine.  I don't have an objection to a progress monitor, particularly if there are cases where the project build blocks for 3+ secs.  We need this fixed in some form by tomorrow, so if a progress monitor is possible by then, let's go with that.  If not, let's disable the Finish button for M4 and look at using the progress monitor for M5.

What do you think?

**Comment by bfitzpat** [comment]
I will look into this today and see what I can do.

**Comment by bfitzpat** [comment]
The issue is that we're doing the camel updates outside the wizard's performFinish. Instead we're doing the work inside the palette class after the wizard's "finish" button is triggered. I'm going to see about moving the camel bits inside the wizard to fix this.

**Comment by bfitzpat** [comment]
@kcbabo Can you verify that this fixes the Finish problem? That work is here: https://github.com/bfitzpat/fuseide/tree/issue179
And I think I have a way to get the maven dependencies working for #180  as well. It's not in yet, but should be relatively easy.

**Comment by kcbabo** [comment]
Will do.

**Comment by kcbabo** [comment]
I tried as hard as I could and couldn't get it to click more than once.  Good to go!

**Comment by kcbabo** [comment]
Just want to confirm that this is ready to go before pushing it.  Let me know and I'll push away.

**Comment by bfitzpat** [comment]
Let me put a PR out there and you can push. Then I'll work on the other bits in a separate branch.

**Comment by bfitzpat** [comment]
https://github.com/fusesource/fuseide/pull/185 is ready for ya

**Comment by kcbabo** [comment]
pushed
