### ISSUE TITLE
Dependencies missing for generated JSON model classes

### ISSUE THREAD

**Issue by kcbabo** [fusesource/fuseide#180]
Generated JSON model classes use Jackson annotations which will not necessarily be on the class path for user projects (i.e. not defined as a dependency in their pom.xml).  Look into adding this capability to the project if the user selects JSON as a source/target type.

**Comment by bfitzpat** [comment]
What are the maven bits for these annotations and we can add them via the palette extension

**Comment by kcbabo** [comment]
We may need a different place to add it because:
* Adding the dependency is only required if JSON is used for a transformation (XML -> XML, XML-> Java, etc. do not need this dependency).
* We still have a standalone wizard to create transformations outside of the palette extension, so we need to add the dependency for that case as well.

**Comment by kcbabo** [comment]
Thinking about this a bit more, we need to include dependencies on the relevant Camel data formats, which will then pull in transitive dependencies we need as well.  
```
<dependency>
      <groupId>org.apache.camel</groupId>
      <artifactId>camel-jaxb</artifactId>
      <version>${version.camel}</version>
    </dependency>
    <dependency>
      <groupId>org.apache.camel</groupId>
      <artifactId>camel-jackson</artifactId>
      <version>${version.camel}</version>
    </dependency>
```

**Comment by kcbabo** [comment]
@bfitzpat  : how hard is it to add these through the new wizard vs the palette extension?  That would allow us to address this in one place and use information from the wizard to determine exactly what needs to be added.

**Comment by lhein** [comment]
I could provide a helper class/method to add a dependency easily without
much magic. The method is already there.

Lars


Am 30.03.2015 um 15:03 schrieb Keith Babo:

**Comment by bfitzpat** [comment]
I'm working on the finish bits in #179

**Comment by lhein** [comment]
MavenUtils.updateMavenDependencies(List<ComponentDependency>)

Part of the camel editor plugin. You can leverage that for adding deps on the fly.

**Comment by bfitzpat** [comment]
Created this PR to handle the dependencies - https://github.com/fusesource/fuseide/pull/188

**Comment by kcbabo** [comment]
pushed
