### ISSUE TITLE
List of expression languages should be editable drop-down

### ISSUE THREAD

**Issue by kcbabo** [fusesource/fuseide#200]
We provide some common options in the drop-down now, but there are other languages available to the user.  Let's make the drop-down for language selection editable so that the user can select a predefined value or enter one on their own (e.g. groovy).

**Comment by lhein** [comment]
We have a model available for Languages, DataFormat and alike. Its available through the camel.model plugin. see https://github.com/fusesource/fuseide/tree/master/core/plugins/org.fusesource.ide.camel.model/src/org/fusesource/ide/camel/model/catalog

You should use that for letting the user choose a language. It also provides the needed maven deps to get the language working.

**Comment by jpav** [comment]
Here are the available languages from Camel:

XQuery
JXPath
Constant
Groovy
Bean method
File
HL7 Terser
ExchangeProperty
Header
XPath
Ref
SQL
EL
OGNL
Simple
XML Tokenize
SpEL
MVEL
Tokenize
JSonPath

**Comment by kcbabo** [comment]
Let's go with this list:
```
XQuery
JXPath
Constant
Groovy
HL7 Terser
ExchangeProperty
Header
XPath
Ref
EL
OGNL
Simple
MVEL
JSonPath
```
If you want to simply update the list you get from the underlying Fuse tooling code, then *remove* these:
```
Bean method
File
SQL
XML Tokenize
SpEL
Tokenize
```

**Comment by kcbabo** [comment]
Couple of other things:
* As we said on the call, no need to make this list editable.  If the user wants to use another language, they can always use a ref: expression.
* Many of these languages require additional Maven dependencies.  I believe that the code Lars has in the core Fuse tooling will add them to the pom.xml if necessary.  We should make sure that happens.

**Comment by kcbabo** [comment]
It appears as though Maven dependencies are not being added for languages such as Groovy as noted in my second bullet point above.

**Comment by jpav** [comment]
Can you give me an idea of what dependency in particular is missing?  The code is already calling org.fusesource.ide.camel.editor.utils.MavenUtils.updateMavenDependencies(), which is supposed to handle this.

**Comment by kcbabo** [comment]
OK, confirmed this is a problem.  To reproduce, use JXPath as the language for an expression mapping which requires the following dependency:
```
    <dependency>
      <groupId>org.apache.camel</groupId>
      <artifactId>camel-jxpath</artifactId>
    </dependency>
```
After adding the expression, the dependency is not present.

**Comment by kcbabo** [comment]
At the end of the day, I don't consider this a blocker, so it's cool if we don't have it in for M5.  @jpav - could you help Brian with https://github.com/fusesource/fuseide/issues/252 - that is a blocker for M5.
