### ISSUE TITLE
Select element for XML where multiple types are available

### ISSUE THREAD

**Issue by kcbabo** [fusesource/fuseide#201]
For XML source and target types, we need to prompt the user to select the actual element they want to use because there's no way to change this after the map is created.  There are a couple scenarios here:
* User provides a schema with multiple top-level element definitions.  We currently choose one with a guess, but we really need the user to tell us which top-level element they are mapping.
* User provides XML instance document where a schema is generated.  There will only be one top-level type, which makes this easier than the schema case, but there will still be multiple classes generated so we need to choose the right one.

For both cases, we need to do a few things:
* On the XML page, we need to allow the user to select the element they care about and stash this selection for performFinish later in the wizard.  If there's only one eligible option (i.e. one top-level element), then we can auto-select the element name for the user.
* In performFinish, we need to look at the generated JCodeModel and grab the names of all classes with an @XmlRootElement annotation.  The element name is available in that annotation, so we can build a map of element names to Java types.  Look the element name up in the map created above and select the Java type that corresponds to it for the transformation enpdoint.

**Comment by jpav** [comment]
WRT your last two points:

* I'm hoping you're implying that if an instance doc is selected, that's a situation where there is only one option that we can automatically determine, regardless of how many top-level elements are defined in the schema.
* I don't understand why we need to filter based on @XmlRootElement if we already know the right element from the wizard.

**Comment by kcbabo** [comment]
If it's an XML instance document, there are potentially many generated classes, but there should only be one with @XmlRootElement.  I need to confirm that, but I'm pretty sure it's the case.  So we can handle that without direct input from the user.  I only mentioned it above because it's still a case we need to code for behind the UI.

We need to search for @XmlRootElement because we need to know the name of the Java class that will be used in the Dozer mapping configuration and the Camel endpoint URI.  So the user selects the element name but they have no idea about classes being generated.  In performFinish() we generate classes, but we don't know (right now) which XML element the user is interested in.  So we need to correlate the user's choice of XML element with the generated classes by using the element name present in the @XmlRootElement annotation.

**Comment by jpav** [comment]
To the latter issue, I guess I was assuming we could figure that out just by matching up the type name with the element name, but maybe that doesn't always work for some reason.

**Comment by kcbabo** [comment]
Possible, but I'm not sure if there are weird cases with JAXB naming.  Having the element name in the annotation is pretty deterministic, but if that turns out to be problematic, then I agree we can use a simple name matching (ignoring case most likely).

**Comment by bfitzpat** [comment]
Do we have any good examples where a schema with multiple top-level element definitions or the schema generated for an instance document creates one? In either case, once the user selects the XML source (and we can introspect the schema or introspect the instance to get some clues as to the schema that will be generated) - we may need some utility methods from the XmlModelGenerator class to help us out. We won't want to go all the way to the generated code level before they hit Finish - so having some way of getting info from the JCodeModel ahead of that would be very useful if we can do it.

**Comment by kcbabo** [comment]
Yep, I can provide some examples.  Before that though, you might want to think about how we are going to prompt the user for the element selection.  Right now, we only display the schema/document in a basic text area.  I guess one approach would be to have a drop-down above the text area which lists the possibilities.  In the case where there's only one element, we can disable the drop-down and just display the only option.

If you want, I can add a convenience method to common which takes a schema or instance document and returns the valid element names.

**Comment by bfitzpat** [comment]
Examples would be awesome. 

Yes, that's what I was thinking for a drop-down box of root elements. If there's only one root, we show that as selected in the list and disable it. Otherwise they can select from the list. Simple and straightforward. And we can update the tooltip to provide some additional feedback (i.e. only one root was found or multiple roots were found, please select one).

And yes please. :)

**Comment by kcbabo** [comment]
OK, @bfitzpat, you're clear for takeoff!
https://github.com/kcbabo/fuseide/commit/8cadae1dce13b77074b89d9241d58668d38c7f15

These two methods will get you the element names to populate the list on the source/target pages:
https://github.com/fusesource/fuseide/blob/master/transformation/common/src/main/java/org/jboss/tools/fuse/transformation/model/xml/XmlModelGenerator.java#L113
https://github.com/fusesource/fuseide/blob/master/transformation/common/src/main/java/org/jboss/tools/fuse/transformation/model/xml/XmlModelGenerator.java#L134

And this method can be used to get a map which has element names as the key and the fully-qualified class name as the value.  This will allow you to select the correct Java class for the source/target types.
https://github.com/fusesource/fuseide/blob/master/transformation/common/src/main/java/org/jboss/tools/fuse/transformation/model/xml/XmlModelGenerator.java#L113

**Important!!**  *The element names in the map are the local part of the element name - no prefix, no namespace URI.  Keep that in mind when you use the value specified by the user on the source/target page to lookup the class name in the map.*

I added a bunch of tests to XmlModelGeneratorTest to validate the implementation and provide an example for you:
https://github.com/fusesource/fuseide/blob/master/transformation/common/src/test/java/org/jboss/tools/fuse/transformation/model/xml/XmlModelGeneratorTest.java

**Comment by bfitzpat** [comment]
Ok. I have this working on the XML page of the New Transformation wizard in this pull request - https://github.com/fusesource/fuseide/pull/246

I have some questions however... 

1. For an XML instance, we only fetch the single root element - is there ever a case where an XML instance might have more than one? (I can't think of one.)

2. The drop-down is only enabled if there is more than one to choose from. Do we want to enable it to show there's only a single root element?

3. Do we need to do anything with the URI portion of the QName? Right now I'm stashing it in the combo, but it doesn't seem we really need to do that.

But I think this does what we want it to do. :)

**Comment by jpav** [comment]
> On Apr 24, 2015, at 4:53 PM, Brian Fitzpatrick <notifications@github.com> wrote:
> 
> Ok. I have this working on the XML page of the New Transformation wizard in this pull request - #246
> 
> I have some questions however...
> 
> For an XML instance, we only fetch the single root element - is there ever a case where an XML instance might have more than one? (I can't think of one.)
> 

No, it wouldn't be a legal instance if it had more than one root. 

> The drop-down is only enabled if there is more than one to choose from. Do we want to enable it to show there's only a single root element?
> 

I've seen this handled both ways, but I prefer the latter because it doesn't beg the question, "why is this field disabled?"

> Do we need to do anything with the URI portion of the QName? Right now I'm stashing it in the combo, but it doesn't seem we really need to do that.
> 

I can't think of a reason why we'd need it either.

**Comment by bfitzpat** [comment]
Ok. thanks for the input @jpav ! - I'll get this updated first thing Monday so we can get it in.

**Comment by jpav** [comment]
BTW, I want to talk to you a bit Monday about the concern you had with the DnD image.  I think I have a way to alter that, but I want to make sure we're on the same page about the expectations.

**Comment by bfitzpat** [comment]
Ok, I've updated the PR to not disable the list after it gets populated. And let's definitely chat about the DnD image and DnD in general.

**Comment by bfitzpat** [comment]
I discovered a funky issue dragging/dropping root nodes this morning, so hold off on the PR for now while I track this down... :(

**Comment by bfitzpat** [comment]
Never mind. Wires crossed. Different issue entirely!!

**Comment by kcbabo** [comment]
pushed
