### ISSUE TITLE
Show Dozer auto-mapped fields

### ISSUE THREAD

**Issue by kcbabo** [fusesource/fuseide#202]
Wondering if we should provide some way to show the fields that will be auto-mapped by Dozer without any changes.  This would be useful if the source and target models are very similar and the user simply needs to account for a few differences when they define mappings.

Probably a stretch goal, but worth discussing in M5.

**Comment by jpav** [comment]
Migrated to JIRA: https://issues.jboss.org/browse/FUSETOOLS-1446
