### ISSUE TITLE
Support for Maps as source/target

### ISSUE THREAD

**Issue by kcbabo** [fusesource/fuseide#203]
Special case of Java source/target is a map of key/value pairs.  Dozer supports it and it's useful for cases in Camel where data is natively returned as a Map (e.g. database bindings).  Figure out how this should look in the editor and map to Dozer config.

**Comment by jpav** [comment]
Replaced by [FUSETOOLS-1478](https://issues.jboss.org/browse/FUSETOOLS-1478)
