### ISSUE TITLE
New Transformation Test  wizard should prompt for Camel configuration

### ISSUE THREAD

**Issue by kcbabo** [fusesource/fuseide#212]
Allow the Camel Context to be selected in the wizard.  Right now, if the actual Camel configuration is not selected in the project explorer, the list of endpoints is not populated.   So this will address that issue and the case where the user has multiple Camel configs in their project.

**Comment by bfitzpat** [comment]
I have this working - there's a new "Camel File Path" field that it tries to populate by default (looking for META-INF/spring/camel-context.xml). But you now have a browse button so you can select another camel file. It then repopulates the Transformation ID drop-down list.

Note in this image that there's a tool tip added to the combo box if there are no transformation endpoints available in the selected camel config. It's not quite as obvious a warning, but it's there to give some indication of why the list is empty. 

![transformation-test-wizard](https://cloud.githubusercontent.com/assets/530878/7126635/19b21f9a-e1f8-11e4-868f-ae4a2e841b3a.png)

**Comment by bfitzpat** [comment]
@kcbabo  - Created PR here - https://github.com/fusesource/fuseide/pull/214 - but happy to make changes if necessary. Do we want to use a similar warning/error style to what we have in the new Transformation Wizard?

**Comment by kcbabo** [comment]
Looks good.  Thanks, Brian!

**Comment by kcbabo** [comment]
pushed
