### ISSUE TITLE
Escape characters should not be displayed for expression mappings

### ISSUE THREAD

**Issue by kcbabo** [fusesource/fuseide#213]
1) Create an expression mapping using the simple language and expression text of ${body}
2) Hover over the expression mapping and notice that the value displayed is "\${body}" instead of "${body}
3) Update the expression mapping by selecting "Set field" in the detail view.  Note that the expression text which you edit also has the escape characters displayed.  If you hit OK, you now end up with doubled escape characters.

**Comment by jpav** [comment]
Pushed
