### ISSUE TITLE
tighten up validation on mappings

### ISSUE THREAD

**Issue by kcbabo** [fusesource/fuseide#218]
I've noticed some weird behavior/errors when assigning from a top-level field to a field within a list.  We need to add some additional validation and probably tighten up the mapping logic in commons to handle cases like:
- Map field to a list : not supported, should not be allowed
- Map list to a field : not supported, should not be allowed
- Map field to a field in a list : this should be supported, currently blows up
- Map field in a list to a higher-level field : I suspect this is broken as well
- Map type to field (e.g. ABCOrder.header to XyzOrder orderId) : should not be allowed, in fact you shouldn't even be able to select a type as a drop source
- Map field to type  : should not be allowed, in fact you shouldn't even be able to drop on a target type

**Comment by kcbabo** [comment]
Here's the associated logic for each check:
Map field to a list : not supported, should not be allowed
```
if (!sourceModel.isCollection() && targetModel.isCollection()) {
  // invalid
}
```
Map list to a field : not supported, should not be allowed
```
if (sourceModel.isCollection() && !targetModel.isCollection()) {
  // invalid
}
```
Map field to a field in a list : not supported
```
if (!sourceModel.getParent().isCollection() && targetModel.getParent().isCollection()) {
  // invalid
}
```
Map field in a list to a higher-level field : not supported
```
if (sourceModel.getParent().isCollection() && !targetModel.getParent().isCollection()) {
  // invalid
}
```
Map type to field (e.g. ABCOrder.header to XyzOrder orderId) : should not be allowed, in fact you shouldn't even be able to select a type as a drop source
```
if (!sourceModel.getChildren().isEmpty && !sourceModel.isCollection()) {
  // invalid
}
```
Map field to type : should not be allowed, in fact you shouldn't even be able to drop on a target type
```
if (!targetModel.getChildren().isEmpty && !targetModel.isCollection()) {
  // invalid
}
```

**Comment by bfitzpat** [comment]
Thanks Keith!

**Comment by kcbabo** [comment]
Recording for posterity:
```
kcbabo: bfitzpat: one other thing to keep in mind here
kcbabo: is that there are actually three ways to set the source or target field for a mapping
kcbabo: 1) drag from source model to target model
kcbabo: 2) drag from source model to empty mapping in mappings list; drag from target model to empty mapping in mappings list
kcbabo: 3) use the setField() dialog in the detail view
bfitzpat: right, so drag/drop validation would take care of 1 & 2 and we should be able to have some additional feedback for 3
```

**Comment by bfitzpat** [comment]
Ok... @kcbabo - Here's my conundrum in more concrete terms... 

If I try to map id to item id in our example...

ABCOrder.orderItems.item.id ---> XyzOrderSchema.lineItems.itemId

id : java.lang.String
isCollection = false
getParent = Item : abcorder.ABCOrder$OrderItems$Item
getParent.isCollection = false

itemId : java.lang.String
isCollection = false
getParent = lineItems : [xyzorderschema.LineItem]
getParent.isCollection = true

if (!id.getParent().isCollection() (false) && itemId.getParent().isCollection() (true)) { true && true == true
  //  this is invalid
}

This is your "Map field to a field in a list : not supported" case...

**Comment by bfitzpat** [comment]
This is what the source model looks like...

sourceModel     Model  (id=170)     
     children     HashMap<K,V>  (id=278)     
     isCollection     false     
     modelClass     null     
     name     "id" (id=279)     
     parent     Model  (id=280)     
          children     HashMap<K,V>  (id=283)     
          isCollection     false     
          modelClass     Class<T> (abcorder.ABCOrder$OrderItems$Item) (id=103)     
          name     "Item" (id=288)     
          parent     null     
          type     "abcorder.ABCOrder$OrderItems$Item" (id=289)     
     type     "java.lang.String" (id=281)

**Comment by bfitzpat** [comment]
This is what the target model looks like...
```
targetModel	Model  (id=268)	
	children	HashMap<K,V>  (id=291)	
	isCollection	false	
	modelClass	null	
	name	"itemId" (id=292)	
	parent	Model  (id=294)	
		children	HashMap<K,V>  (id=296)	
		isCollection	true	
		modelClass	null	
		name	"lineItems" (id=298)	
		parent	Model  (id=299)	
		type	"[xyzorderschema.LineItem]" (id=301)	
	type	"java.lang.String" (id=281)	
```

**Comment by kcbabo** [comment]
I'm going to have to see the code and walk through in the debugger.  When I parse the ABCOrder class into a model using ModelBuilder, the parent model for "id" (the source model above) shows isCollection = true.

**Comment by bfitzpat** [comment]
PR is ready to go - https://github.com/fusesource/fuseide/pull/239

Users are now unable to map invalid combinations via:
* Drag from Source model to Transform model
* Drag from Source model to Transformations (middle) 
* Drag from Target model to Transformations (middle)
* Drag Source model to Details pane (bottom)
* Drag Target model to Details pane (bottom)
* And when using the Set Field dialog

**Comment by bfitzpat** [comment]
The drag cursor does not change to the "invalid" (circle with line through it) when dragging to the middle or the bottom. I'm not quite sure how to change it at this point, since it's a very custom chunk of code handling drag/drop in those cases. 

@jpav might have some ideas

But we don't commit the change if it's not valid at this point.

**Comment by kcbabo** [comment]
pushed
