### ISSUE TITLE
Data Transformation: Add "Expand" tool item

### ISSUE THREAD

**Issue by tsedmik** [fusesource/fuseide#234]
There is no tool item for expand the whole tree (only _collapse_ is present). It would be useful to have one.

![trans](https://cloud.githubusercontent.com/assets/5408450/7272968/71008f54-e8ef-11e4-856f-795be3abb8d9.png)

**Comment by jpav** [comment]
We've have intentionally not done this for a couple of reasons:

* This is a very minor reason, but not having an expand all button is consistent with other views in Eclipse. But the most important reason is...

* We don't currently have any way to manage memory well wrt large models.  We have lots of experience with large, expanded models using all of available memory and crashing the entire Eclipse platform.
