### ISSUE TITLE
Data Transformation: Search not working

### ISSUE THREAD

**Issue by tsedmik** [fusesource/fuseide#235]
_Search_ seems to be broken. I type something, click on "Search" and nothing happened.

![search](https://cloud.githubusercontent.com/assets/5408450/7273001/ea544396-e8ef-11e4-9540-e32670028b37.png)

**Comment by kcbabo** [comment]
This is because it's not implemented yet. :-)  We were just discussing this in the dev call yesterday and @jpav is going to look at whether it can be implemented in M5.  If not, we will remove the search box from the editor for 6.2.
