### ISSUE TITLE
Data Transformation: Remove 'Fuse Transformation' duplicity in 'New' wizard

### ISSUE THREAD

**Issue by tsedmik** [fusesource/fuseide#238]
In _File --> New --> Other_ is _Fuse Transformation_ in _Fuse Tooling_ category (that is correct) and out of any category (should be removed)

![screenshot from 2015-04-22 13 36 48](https://cloud.githubusercontent.com/assets/5408450/7273523/de18e1ea-e8f4-11e4-8868-affb136e8f25.png)

**Comment by kcbabo** [comment]
I agree - this is no longer needed now that we are part of the Fuse Tooling category.

**Comment by icamposjurado** [comment]
Hi,
I don't have available in my JBoss Developer the Fuse Tranformation and in the camel palette, I don't have the Data Transformation. Please, cound you tell me how can I get this option? Is a new update?
Thanks in advance, regards.

**Comment by lhein** [comment]
Have a look at our GitHub wiki. There is an install guide.

Cheers
Lars
 Am 24.04.2015 09:48 schrieb "icamposjurado" <notifications@github.com>:

**Comment by icamposjurado** [comment]
Hi Lars, 

thanks a lot for the answer, really I don't see the install guide. I found the 
https://github.com/fabric8io/data-mapper/wiki/Tooling-Installation But I think it is another thing. I looking for the Data Transformation tool.
Thanks a lot in advance, regards.
Iñaki

**Comment by lhein** [comment]
Look at GitHub.com/fusesource/fuseide

Lars
 Am 24.04.2015 10:30 schrieb "icamposjurado" <notifications@github.com>:

**Comment by icamposjurado** [comment]
Thanks again for the answer. 
Is there a plugging inside GitHub.com/fusesource/fuseide to import in JBOss Developer Studio where is the Data Transformation in the palette? I watched the video about Milestone 4, but only import a project. Is available a pluggions to upload?
Thanks a lot in advance, cheers.

Iñaki

**Comment by icamposjurado** [comment]
Hi,
I got it. Installing a Nightly Build.
Thanks a lot for the help.

Iñaki

**Comment by bfitzpat** [comment]
Created PR https://github.com/fusesource/fuseide/pull/248 to remove the extra wizard entry

**Comment by kcbabo** [comment]
pushed
