### ISSUE TITLE
Restrict listing for Camel Context path to just Camel Context definitions

### ISSUE THREAD

**Issue by kcbabo** [fusesource/fuseide#247]
When the user launches the Fuse Transformation wizard using File -> New, she must select the path to the Camel Context configuration since we don't know which config is being targeted (this is not the case when the wizard is launched from the palette extension).  Right now, we show all XML files, but there is a way (used by the Fuse Transformation Test wizard) to filter the list to only include Camel Context files.

**Comment by bfitzpat** [comment]
Created PR https://github.com/fusesource/fuseide/pull/249 

Not only does this work more like the New Transformation Test wizard (where we check the list of xml files in the workspace or project and only show blueprint or spring-based camel files) but now when the user specifies the camel file and they haven't previously selected a project, we get the project from the selected file and select it for them.

**Comment by kcbabo** [comment]
pushed
