### ISSUE TITLE
Add validation for field and variable mappings

### ISSUE THREAD

**Issue by kcbabo** [fusesource/fuseide#252]
Now that we have some great field mapping validation in place, we should add some for variable and expression mapping as well.  Some rules that apply to both expression and variable mappings that we should enforce:
* The target of the mapping cannot be a parent type (e.g. XYZOrder).  I tried this and got an NPE.
* The target cannot be a list.
* The parent of the target field cannot be a list.

All of the above can probably be boiled down to not allow a mapping for variables/expressions if either of the following conditions holds true:
* Target field getChildren().size() > 0
* Target field getParent() == null || getParent().getChildren().size() > 0

**Comment by bfitzpat** [comment]
@jpav  - Ok, I lost myself in a maze of code and got tangled up in validation. I've updated my method to be more forgiving... Here's the PR - https://github.com/fusesource/fuseide/pull/261

But I am out of ideas as far as validating the actual drop targets using this thing. Nothing I tried worked consistently. Can you take a look?
