### ISSUE TITLE
Data Transformation: Improve details of a transformation

### ISSUE THREAD

**Issue by tsedmik** [fusesource/fuseide#262]
To improve user experience, I suggest to slightly modify details of a transformation (see pictures below).
  1. remove the gray rectangle on left side
  2. show the arrow in the rectangle on right side always
  3. align the rectangle

Current:
![current](https://cloud.githubusercontent.com/assets/5408450/7387409/13133df6-ee5d-11e4-8d4d-bf7192eb92a5.png)
Modifications:
![modification](https://cloud.githubusercontent.com/assets/5408450/7387415/18e587d4-ee5d-11e4-8d72-4060e0b85464.png)
Final:
![final](https://cloud.githubusercontent.com/assets/5408450/7387416/1a88b732-ee5d-11e4-94d2-478ff44fc521.png)

**Comment by jpav** [comment]
@bfitzpat: Do you see the same light gray backgrounds that are shown here (i.e., the background of the "ABCOrder" label, the arrow backgrounds, etc.)?  On the Mac, I do not.

**Comment by bfitzpat** [comment]
Yes. I see the light gray backgrounds on the labels also.

**Comment by jpav** [comment]
@bfitzpat: Could you change MappingDetailViewer.createDetailPane to explicitly set the label's background to the parent pane's background, and let me know if that fixes the color difference for that label (which displays the model name)?

**Comment by bfitzpat** [comment]
Yes, not the background, but the foreground works -         label.setBackground(pane.getForeground());

**Comment by jpav** [comment]
Yes, sorry, that’s what I should have said.  I forgot those rounded rectangles use the foreground to paint their rounded “background”.
So, now that I know my theory is correct, can you attach a screenshot of your editor with a mapping selected so I can address all of the weird background issues?

**Comment by bfitzpat** [comment]
![editor-background-issues](https://cloud.githubusercontent.com/assets/530878/7457852/d2739d92-f24c-11e4-8ab4-982258b986e6.png)

**Comment by bfitzpat** [comment]
Hey @jpav - here's what it looks like now. You can see the background on the blue arrow in the Transformations list (that's what I mentioned on the call). It looks better with the backgrounds as far as your PR. 

My one concern is the arrow for the drop-down. You can't see it at all unless you hover over the shaded area. Is that as designed? As a user, I'm not sure I'd know to hover over it, which hides a whole chunk of functionality. 

I also wonder if we could resize the white text field itself so it's more consistent left to right. I think as the shape grows, the tiny little field may look funky as well.

![improved-backgrounds](https://cloud.githubusercontent.com/assets/530878/7480265/a8ad3d3c-f324-11e4-8472-240b2aeedf3a.png)

**Comment by jpav** [comment]
> Hey @jpav <https://github.com/jpav> - here's what it looks like now. You can see the background on the blue arrow in the Transformations list (that's what I mentioned on the call).
> 

Yeah, missed that; I’ll fix it.

> My one concern is the arrow for the drop-down. You can't see it at all unless you hover over the shaded area. Is that as designed? As a user, I'm not sure I'd know to hover over it, which hides a whole chunk of functionality.
> 

This is absolutely by design, and is borrowed for other apps that work similarly to reduce unnecessary visual “noise".  Yes, it’s not immediately obvious it’s there, but the expectation is the user will quickly find the functionality with normal mouse movement.  I think its more than reasonable that a user will do something with the mouse over most of the fields shown just to see what’s possible the first time they use it, such as is there a context menu (which are also never visible to begin with).  In fact, the whole idea of icons showing up “on the fly” is exactly to replace the need for context menus.

> I also wonder if we could resize the white text field itself so it's more consistent left to right. I think as the shape grows, the tiny little field may look funky as well.
> 

Yeah, I can do something with that, too.

**Comment by bfitzpat** [comment]
Cool. Thanks John!

**Comment by bfitzpat** [comment]
Looks great John!
