### ISSUE TITLE
Some of the quickstarts can't be launched

### ISSUE THREAD

**Issue by cmoulliard** [fusesource/fuseide#263]
I would like to warn guys that we propose a list of maven camel / cxf / fabric8 ... archetypes when a Fuse project is created but some of them can't be started locally using `run as camelcontext` as they have been designed using Apache Aries Blueprint XML file and that the pom xml file  is not configured with the right dependencies to start/launch the project locally with pojosr. 

We have different possibilities to improve that situation :  
* Update the "blueprint" archetypes to mention into the README file that they can't be launched locally (this is certainly a bad thing as we tried to promote to use JBDS as tool to design/run Camel routes).
* Update the archetypes to allow them to be launched locally. Take care that pojosr should be certainly improved as some bundles are looking about OSGI Services and maven dependencies should be reviewed for each "blueprint" archetype
* Spring could be used instead of Blueprint to avoid to start a dummy OSGI container

**Comment by lhein** [comment]
I am closing this issue because we no longer use the archetypes. We got now our own templates. If you got the time Charles it would be really awesome if you can give them a try.
