### ISSUE TITLE
Keyboard navigation/shortcuts

### ISSUE THREAD

**Issue by bfitzpat** [fusesource/fuseide#284]
While doing some testing, I noticed a couple of things while working in the editor. Tabbing around works great, but...

1. It would be nice if you could hit the Delete key while tabbing through the Transformations list to delete a mapping.
2. It would be nice if there was a shortcut for creating new fields as well in the Transformations list. 
3. It would be nice if you could pop up the drop-down menu in the Details view using a keyboard shortcut as well.

Definitely "nice to have" - but might be expected by keyboard users.

**Comment by bfitzpat** [comment]
Might also be good to auto-select the next or previous mapping when you delete one so that once we have the Delete key hooked up you can just hit it 5 times to delete 5 mappings. Unfortunately that also may involve adding some undo/redo functionality, which I think the editor needs.

**Comment by bfitzpat** [comment]
Being able to use the up and down arrows to navigate in the Transformations list and possibly even Page Up/Page Down or Home/End for quicker access would also be handy.

**Comment by kcbabo** [comment]
https://issues.jboss.org/browse/FUSETOOLS-1365
