### ISSUE TITLE
Allow customization of model viewer tree when used on Transformation wizard pages

### ISSUE THREAD

**Issue by bfitzpat** [fusesource/fuseide#288]
When the Model Viewer control is used on a wizard page, as in the New Transformation wizard, as it is on the Java page of the wizard, it would be nice to be able to:

* Choose which toolbar buttons are visible. Collapse All, Show/Hide types, and the Search field would be good, but the Hide/Show Mapped Fields button makes no sense in this context.
* Change the background on the toolbar buttons to remove the gray color

**Comment by bfitzpat** [comment]
![wizard-page-java](https://cloud.githubusercontent.com/assets/530878/7482740/e1d67c2e-f336-11e4-8971-a1211c8a46d6.png)

**Comment by jpav** [comment]
The latter should have already been taken care of by the fix for issue #262.

**Comment by bfitzpat** [comment]
Beautiful. :)

**Comment by kcbabo** [comment]
https://issues.jboss.org/browse/FUSETOOLS-1363
