### ISSUE TITLE
Improve New Transformation Test Wizard Validation

### ISSUE THREAD

**Issue by bfitzpat** [fusesource/fuseide#292]
Found a case with the Test wizard.

To reproduce, copy the Starter project and create a new Transformation with a new endpoint in the Camel Spring file.

1) With nothing selected in the Project Explorer, open the Test wizard. Don't set any fields.
2) Click Browse for the Camel File Path. 
3) Pick the Camel spring file (camel-context.xml). Click OK.
4) Select your Transformation endpoint ID.

You should NOT be able to proceed, but the Finish button is enabled. And if you click it, you getting an error. (No exception logged in the Error Log however, so I'm not sure if it's the exact one.)

**Comment by bfitzpat** [comment]
This is sort of related to #253

**Comment by bfitzpat** [comment]
Ok... Have issued a PR that should address the remaining issues with validation... https://github.com/fusesource/fuseide/pull/293

I'm hoping that this buttons up any lingering issues left over after #253 

New things... 1) the camel file text box is now read only, meaning you can only select via the file browse button and 2) when you select via the file browse button, it automatically sets the project and test folders

**Comment by kcbabo** [comment]
If the directory src/test/java does not exist in the project the Finish button is not enabled.  This is a problem now that it defaults to src/test/java and the user has no way to create that directory once inside the wizard.

I pushed the pull request associated with this issue already, so we should address this new problem with a separate commit (feel free to use the same issue # for tracking purposes).

**Comment by bfitzpat** [comment]
Hmmm. Ok, will address.

**Comment by kcbabo** [comment]
pushed
