### ISSUE TITLE
Transformation Test wizard won't enable finish button if directory doesn't exist

### ISSUE THREAD

**Issue by bfitzpat** [fusesource/fuseide#295]
If the directory src/test/java does not exist in the project the Finish button is not enabled. This is a problem now that it defaults to src/test/java and the user has no way to create that directory once inside the wizard.

Side effect of #292

**Comment by bfitzpat** [comment]
This revealed a couple of other interesting quirks.

1) If you change the name of your camel configuration file, the generated test is invalid because it was looking for specific filenames for blueprint or spring.
2) If you try to test a blueprint camel config, the "camel-test-blueprint" dependency is missing from the Starter project. Do we want to add it?

**Comment by bfitzpat** [comment]
Created PR https://github.com/fusesource/fuseide/pull/297 for this one. May want to open a different PR for issue 2 in the comment above.

**Comment by kcbabo** [comment]
pushed
