### ISSUE TITLE
Add blueprint test dependency when blueprint unit test is created

### ISSUE THREAD

**Issue by kcbabo** [fusesource/fuseide#299]
We need to add a Maven dependency on the blueprint test support in Camel if a user creates a Transformation Test for a Camel blueprint configuration and that dependency does not exist in the project already.

**Comment by bfitzpat** [comment]
Created PR here - https://github.com/fusesource/fuseide/pull/307 but I don't know if it works. The Mars TP has me unable to run anything at this moment. If anyone has a chance to test this in a working environment, let me know. It *SHOULD* work.

**Comment by bfitzpat** [comment]
Ok. Now with Mars TP issues resolved, I was able to test and fix this further. The PR has been updated - https://github.com/fusesource/fuseide/pull/307
