### ISSUE TITLE
Detect cycles in model parse and mappings

### ISSUE THREAD

**Issue by kcbabo** [fusesource/fuseide#301]
A reference cycle currently leads to a StackOverflowException in the ModelBuilder.  We should detect cycles and not spill into an infinite recursion when building up child models.

**Comment by kcbabo** [comment]
Hit this for the second time in less than a week when trying out example models from users.  We need to fix this in 7.3.0.

**Comment by jpav** [comment]
Depending on how you address this, we may also need to do some work in the GUI to prevent the user from navigating into cyclic structures and creating mappings below the "root" of those cycles.

**Comment by kcbabo** [comment]
pushed
