### ISSUE TITLE
Allow model package exclusion rules to be configured by end users

### ISSUE THREAD

**Issue by kcbabo** [fusesource/fuseide#302]
We have a list of exclusions within ModelBuilder that identify types as being "base" or "opaque" types that we do not parse to pull out child models.  

https://github.com/fusesource/fuseide/blob/master/transformation/common/src/main/java/org/jboss/tools/fuse/transformation/model/ModelBuilder.java#L80

It's quite possible that users will want to configure this to reflect model-specific requirements (e.g. exclude all "org.example.internal").

**Comment by jpav** [comment]
Replaced by [FUSETOOLS-1477](https://issues.jboss.org/browse/FUSETOOLS-1477?filter=12324735)
