### ISSUE TITLE
Improve workflow for changing source/target models

### ISSUE THREAD

**Issue by kcbabo** [fusesource/fuseide#313]
Let's take an example where the transformation source is an XML schema.  If the user makes changes to that schema, they need to:
- Regenerate the model classes using JAXB
- Update mappings that are impacted as a result of the model change

We should consider if/how we can help with this workflow.  At the very least, we should document this use case, steps required, and known gotchas/limitations.

**Comment by jewzaam** [comment]
+1 docs are a great start.  Updating XSDs is a common use case for us.

**Comment by jpav** [comment]
Migrated to JIRA: https://issues.jboss.org/browse/FUSETOOLS-1430
