### ISSUE TITLE
Provide a way to reset the ModelViewer's model input and clear the viewer

### ISSUE THREAD

**Issue by bfitzpat** [fusesource/fuseide#319]
While working on FUSETOOLS-1331, I hit upon a strange case where I needed to reset the ModelViewer (org.jboss.tools.fuse.transformation.editor.internal.ModelViewer) on the JavaPage in the New Transformation Wizard. I tried simply setting the model to null and it blew chunks, so I came up with this little workaround.

https://github.com/bfitzpat/fuseide/blob/FUSETOOLS-1331/transformation/plugins/org.jboss.tools.fuse.transformation.editor/src/main/java/org/jboss/tools/fuse/transformation/editor/internal/wizards/JavaPage.java#L304

It would be great if there was a way just to clear the ModelViewer. It's not a case that will come up often, but a useful one nonetheless.

My workaround creates a model tree with an empty leaf. It's crude, but effective.

**Comment by kcbabo** [comment]
https://issues.jboss.org/browse/FUSETOOLS-1361
