### ISSUE TITLE
unable to build - cannot resolve dependencies

### ISSUE THREAD

**Issue by carljmosca** [fusesource/fuseide#324]
I am trying to build the fuseide on OS X.  I have tried Java 6, 7 and 8 (all with maven 3.2.3).  I am missing some dependencies:

[ERROR]   Missing requirement: org.fusesource.ide.server.extensions.feature.feature.group 8.0.0.qualifier requires 'org.eclipse.tm.terminal.view 2.4.100' but it could not be found
[ERROR]   Cannot satisfy dependency: org.fusesource.ide.jmx.feature.feature.group 8.0.0.qualifier depends on: org.fusesource.ide.server.extensions.feature.feature.group 8.0.0

**Comment by lhein** [comment]
I am afraid the master branch is currently broken. 
You could try the 7.3.x branch or alternatively see https://github.com/fusesource/fuseide/wiki/Installing-a-Nightly-Build.

**Comment by carljmosca** [comment]
Neither option will help me as I continue to try to learn why some newly added component properties are not displayed in the advanced properties page of the designer in 8.x but thanks for the reply.

**Comment by lhein** [comment]
Maybe you can elaborate your problem a bit more detailed and I try to help you.

**Comment by carljmosca** [comment]
I have added a couple of properties to the Google Calendar Component.  There's a bit more about that here: https://issues.apache.org/jira/browse/CAMEL-8777  

The issue is that all of the appropriate properties appear in the Advanced Properties tab except the two I added.

I have, since this submission, added JavaDocs to the properties thinking that, along with the annotation, would get the properties recognized.

While I realize the Google Calendar component is not yet officially supported, I am wondering if it would be worth creating a simple component, testing it, and then add a couple more.  We saw what I think is similar behavior with the MuleSoft designer (also Eclipse based) which was/is some sort of cache problem.

TIA,
Carl

**Comment by lhein** [comment]
The advanced properties for standard camel components are generated for each camel version supported by the tooling. That means if you added properties to a component and you want them to show up in your advanced properties you need to generate the model manually.

In the tools/ide-buildtools we have a maven module which does that by invoking mvn compile exec:java inside. It will generate an xml model out of what Camel provides. 

See https://github.com/fusesource/fuseide/tree/master/core/plugins/org.fusesource.ide.camel.model/catalogs

I guess you are working with local snapshots? If yes, you would need to generate the catalog model using your snapshot version as camel version. Another way would be to add your fields manually to the components.xml file.
Usually we generate those metamodel files only once for a version from our side.

Hope that sheds some light on the issue.

Lars

**Comment by lhein** [comment]
For non-standard camel components we provide an extension point. 
See https://github.com/fusesource/fuseide/blob/master/editor/plugins/org.fusesource.ide.camel.editor/plugin.xml#L298-L314

**Comment by carljmosca** [comment]
Thank you Lars.  Yes, that sheds a whole lot of light on the issue for me and nicely provides me options on how to update and test going forward - much appreciated.

Regards,
Carl

**Comment by lhein** [comment]
Great, let me know if I can help further.
