### ISSUE TITLE
Camel editor in Eclipse Mars

### ISSUE THREAD

**Issue by ronnyaerts** [fusesource/fuseide#332]
I used the fuse-tooling in Eclipse Luna for some time now and this worked very well for my and my colleagues. 

I colleague of mine pointed me that the JBoss Tools were not available for Luna any more so I wrote a new installation procedure for Eclipse Mars. 
I downloaded and installed the 64-bit Eclipse IDE for Java EE Developers (Mars). I added the JBoss Tools (Mars) 4.3.0.Beta1 (using the marketplace) and installed the fuse-tooling from http://download.jboss.org/jbosstools/updates/integration/mars/integration-stack/fuse-tooling/8.0.0/all/repo/. 
The installation was ok but eclipse does not recognise my camel context files as camel things and also the camel editor is not used. 

Do I need to do something special with the Mars version?

**Comment by lhein** [comment]
Ronny,

I'd stick for the moment with the tooling for Luna. We currently have some refactoring ongoing for being compatible with Eclipse Mars. That will take some time. 

JBoss Fuse Tooling has been released as part of the JBoss Tools Integration Stack (JBDSIS 8.0.2) last week, so you can just install JBoss Developer Studio 8 and then from the JBoss Central you can choose the "Software/Update" tab and look for Fuse there.

We also have a wiki page here on github for installing the latest Luna build into default eclipse but I am unsure if thats still working. But maybe worth a check too.

I will update this issue once we have the Mars build set up and ready to use.

Hope that helps,
Lars

**Comment by lhein** [comment]
Ronny,
meanwhile the nightly master build should be ready for install into Mars.
