### ISSUE TITLE
Provide a Name for DoucleClickFeature

### ISSUE THREAD

**Issue by apupier** [fusesource/fuseide#342]
provide a name for https://github.com/fusesource/fuseide/blob/7.3.x/editor/plugins/org.fusesource.ide.camel.editor/src/org/fusesource/ide/camel/editor/features/custom/DoubleClickFeature.java
otherwise it will be badly displayed in contextual menui for Undo/Redo (see screenshot attached)

**Comment by apupier** [comment]
![fuseissue](https://cloud.githubusercontent.com/assets/1105127/8916049/387597b4-34a9-11e5-9ced-4d9f5c6af792.png)

**Comment by lhein** [comment]
Nice catch! Atm this feature just delegates the dbl click event to other plugins which use the appropriate extension point. The only known impl atm is the data transformation editor which simply opens up another editor with another file when doing the dbl click. Nothing you would like to undo. So for the moment we disable the undo for that action until we find a suitable way to get nice namings from the implementing plugins.

Thanks for reporting the issue!

Lars
