### ISSUE TITLE
Cannot RUN CXF Contract First Projects.

### ISSUE THREAD

**Issue by Namphibian** [fusesource/fuseide#407]
Using JBOSS Dev Studio 8.1.0 GA. 
Creating a new Fuse Project using CXF Contract first approach. When trying to debug the project I am getting the following error:

Downloading: http://download.eng.bos.redhat.com/brewroot/repos/jb-fuse-6.2-build/latest/maven/commons-collections/commons-collections/3.2.1.redhat-7/commons-collections-3.2.1.redhat-7.pom

From what I can see the download.eng.ros.redhat.com url is not public facing. Other basic projects run fine. 

This is a stock standard JBOSS Dev install nothing custom except the TFS Everywhere Exploder from MS corp which I need for work.

How do I go about resolving this issue?

**Comment by Namphibian** [comment]
Close this issue it is a non issue. The @#$@#%#$!@#!@%#! MS plugin breaks JBoss studio. I did not want to install it but was forced. Reverted my install to a day or so ago all is smooth sailing! Sorry about the grawlix!

**Comment by lhein** [comment]
Good to hear you figured it out.
