### ISSUE TITLE
Missing xsd file to generate jaxb classes (csv-to-xml, xml-to-csv, ...)

### ISSUE THREAD

**Issue by cmoulliard** [fusesource/fuseide#410]
The csv-to-xml example (and xml-to-csv example too) doesn't include the xsd file required to generate the Account.java, Company.java & Contact.java classes

see here https://github.com/fusesource/fuseide/tree/master/examples/transformation/csv-to-xml/src/main/resources

**Comment by jpav** [comment]
Charles, we’ve discovered a problem with the latest build for 7.3.2 (which I’m assuming is what you’re using).  Once we get that fixed, I’ll be able to figure out what you’re running into, so please bear with me…

**Comment by jpav** [comment]
The files you’re looking for are in a different folder: https://github.com/fusesource/fuseide/tree/master/examples/transformation/csv-to-xml/src/data
