### ISSUE TITLE
Can't select xsd, json, ... files to create the Dozer Transformation.xml & generate the Java classes

### ISSUE THREAD

**Issue by cmoulliard** [fusesource/fuseide#411]
I'm using JBDS Version: 9.0.0.GA (but can also reproduce the problem with JBDS 8.1) & Fuse Tooling - 8.0.0.Alpha1-v20150916-1544-B608 and when I design a mapping between a SourceA and SourceB, I can't select the files located under src/main/resources/META-INF/spring. This problem also exist if I move the source files under a different directory OR If I create a working set

![screenshot 2015-12-08 16 51 58](https://cloud.githubusercontent.com/assets/463790/11679720/a1eb9a22-9e53-11e5-9941-338078b4d617.png)
![screenshot 2015-12-08 16 55 16](https://cloud.githubusercontent.com/assets/463790/11679721/a1edeffc-9e53-11e5-9f67-0fafafdf1b82.png)

**Comment by bfitzpat** [comment]
The latest Fuse tooling is now available with JBoss Developer Studio Integration Stack (JBDSIS 8.0.4) in the Eclipse Marketplace - marketplace.eclipse.org/content/red-hat-jboss-developer-studio-integration-stack-luna

We did have some issues in the Alpha release of the tooling, but they have been resolved.

**Comment by bfitzpat** [comment]
That's for Luna. You can also grab the latest Mars build of the Fuse tooling here - http://download.jboss.org/jbosstools/mars/integration/updates/integration-stack/fuse-tooling/8.0.0.MASTER/all/repo/ - but it is not fully tested yet.

**Comment by bfitzpat** [comment]
Hope that helps!

**Comment by apodhrad** [comment]
Note that it works in JBDS 8.1.0.GA with JBDS-IS 8.0.4.GA (contains Fuse tooling 7.3.2.FINAL)
