### ISSUE TITLE
JBoss Fuse Tooling Apache Camel Editor 8.0.0.v20150814-1750-H2-Alpha1 install problem

### ISSUE THREAD

**Issue by ronnyaerts** [fusesource/fuseide#471]
I picked up the FuseIDE plugin installation again for Eclipse Mars and have a problem with it. 

What I did:
- I installed 64-bit Mars 2 from download eclipse-jee-mars-2-win32-x86_64.zip. 
- I installed JBoss Tools 4.3.0.Final from the Eclipse Marketplace.
- Eclipse Help > Install New Software... > and entered http://download.jboss.org/jbosstools/updates/integration/mars/integration-stack/fuse-tooling/8.0.0/all/repo/ this gaves me the install-1.png screen. 
![install-1](https://cloud.githubusercontent.com/assets/6245529/13702748/1a6b72ac-e791-11e5-907a-6d53eaaedda2.PNG)
- I click "Show original error and build my own solution". This gives the "Install Remediation Page" and details:

Your original request has been modified.
  "JBoss Fuse Tooling Core Bundles Developer Resources" will be ignored because it is already installed.
  "JBoss Fuse Tooling Core Bundles" will be ignored because it is already installed.
Cannot complete the install because one or more required items could not be found.
  Software being installed: JBoss Fuse Tooling Apache Camel Editor 8.0.0.v20150814-1750-H2-Alpha1 (org.fusesource.ide.camel.editor.feature.feature.group 8.0.0.v20150814-1750-H2-Alpha1)
  Missing requirement: Fuse Camel Editor Plugin 8.0.0.v20150814-1750-H2-Alpha1 (org.fusesource.ide.camel.editor 8.0.0.v20150814-1750-H2-Alpha1) requires **'bundle org.eclipse.graphiti 0.13.0' but it could not be found**
  Cannot satisfy dependency:
    From: JBoss Fuse Tooling Apache Camel Editor 8.0.0.v20150814-1750-H2-Alpha1 (org.fusesource.ide.camel.editor.feature.feature.group 8.0.0.v20150814-1750-H2-Alpha1)
    To: org.fusesource.ide.camel.editor [8.0.0.v20150814-1750-H2-Alpha1]

How can I solve this?

**Comment by lhein** [comment]
Hey Ronny,
you are missing Graphiti 0.13 it seems. Please try to install from this site:
http://tools.jboss.org/downloads/jbosstools_is/mars/4.3.0.Beta1.html

**Comment by ronnyaerts** [comment]
Solved.
